name: Basic build and push to Docker hub

on: 
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build container
      run: "docker build --no-cache -t ${GITHUB_REPOSITORY}:${GITHUB_SHA} ."

    - name: Run container
      run: "docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro ${GITHUB_REPOSITORY}:${GITHUB_SHA}"

    - name: Run test
      run: "docker exec test-container ansible --version"

    - name: Login to docker hub
      run: "echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin"

    - name: Push to registry
      run:  "docker push ${GITHUB_REPOSITORY}:${GITHUB_SHA}"
